# Generated by Django 4.2 on 2023-04-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.URLField()),
                ('description', models.TextField()),
                ('game_url', models.URLField()),
                ('genre', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
