# Generated by Django 4.2 on 2023-04-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games_data',
            name='storepage_url',
            field=models.URLField(null=True),
        ),
    ]
