# Generated by Django 4.2 on 2023-04-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_site_app', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='game_id',
            new_name='game',
        ),
    ]
