# Generated by Django 4.2 on 2023-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_site_app', '0005_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_description',
            field=models.CharField(max_length=1000),
        ),
    ]
